package dk.medcom.video.api.service.model;

public record SchedulingTemplateRequestModel(Long conferencingSysId,
                                             String uriPrefix,
                                             String uriDomain,
                                             boolean hostPinRequired,
                                             Long hostPinRangeLow,
                                             Long hostPinRangeHigh,
                                             boolean guestPinRequired,
                                             Long guestPinRangeLow,
                                             Long guestPinRangeHigh,
                                             int vMRAvailableBefore,
                                             int maxParticipants,
                                             boolean endMeetingOnEndTime,
                                             Long uriNumberRangeLow,
                                             Long uriNumberRangeHigh,
                                             String ivrTheme,
                                             boolean isDefaultTemplate,
                                             boolean isPoolTemplate,
                                             String customPortalGuest,
                                             String customPortalHost,
                                             String returnUrl,
                                             VmrTypeModel vmrType,
                                             ViewTypeModel hostView,
                                             ViewTypeModel guestView,
                                             VmrQualityModel vmrQuality,
                                             boolean enableOverlayText,
                                             boolean guestsCanPresent,
                                             boolean forcePresenterIntoMain,
                                             boolean forceEncryption,
                                             boolean muteAllGuests,
                                             DirectMediaModel directMedia) {
}
