services:
   mysql:
     image: mariadb:10.6
     environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=videodb
      - MYSQL_USER=orguser
      - MYSQL_PASSWORD=secret1234
     healthcheck:
      test: mysql --user=orguser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 50
     ports:
      - "3306:3306"
   videoapiservice:
# NB: NATS/Jetstream mangler for at servicen kan starte
     image: kvalitetsit/medcom-video-api:latest
     environment:
      - jdbc_url=jdbc:mariadb://mysql:3306/videodb?useSSL=false
      - jdbc_user=orguser
      - jdbc_pass=secret1234

      - userservice_url=""
      - userservice_token_attribute_organisation="dk:medcom:organisation_id"
      - userservice_token_attribute_username="dk:medcom:email"
      - userservice.token.attribute.email="dk:medcom:email"
      - userservice.token.attribute.userrole="dk:medcom:video:role"
      - userservice.token.attribute.auto.create.organisation=""

      - scheduling.template.default.conferencing.sys.id=22
      - scheduling.template.default.uri.prefix=""
      - scheduling.template.default.uri.domain="vconf-test.dk"
      - scheduling.template.default.host.pin.required=true
      - scheduling.template.default.host.pin.range.low=10000
      - scheduling.template.default.host.pin.range.high=99999
      - scheduling.template.default.guest.pin.required=true
      - scheduling.template.default.guest.pin.range.low=10000
      - scheduling.template.default.guest.pin.range.high=99999
      - scheduling.template.default.vmravailable.before=15
      - scheduling.template.default.max.participants=0
      - scheduling.template.default.end.meeting.on.end.time=false
      - scheduling.template.default.uri.number.range.low=10000
      - scheduling.template.default.uri.number.range.high=99990
      - scheduling.template.default.ivr.theme=10
      - scheduling.info.citizen.portal=""

      - mapping.role.provisioner="meeting-provision"
      - mapping.role.admin="meeting-admin"
      - mapping.role.user="meeting-user"
      - mapping.role.meeting_planner="meeting-planner"

      - organisation.service.enabled=false
      - organisation.service.endpoint=""
      - organisationtree.service.endpoint=""

      - short.link.base.url=""

      - overflow.pool.organisation.id=0

      - ALLOWED_ORIGINS=""
      - audit.nats.url=""
      - audit.nats.subject=""
      - audit.nats.disabled=true
      - events.nats.subject.scheduling-info=""

      - event.organisation.filter="some_random_org_that_does_not_exist"
      - pool.fill.organisation.user="some@email"
      - pool.fill.organisation="some_org"
      - pool.fill.interval="PT1M"
      - LOG_LEVEL=debug
     depends_on:
      mysql:
       condition: service_healthy
   documentation-and-test:
     image: kvalitetsit/medcom-video-api-documentation:latest
     environment:
      - BASE_URL=/test
     ports:
      - 80:8080
