version: '2.1'
services:
   mysql:
     image: mysql:5.7
     environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=videodb
      - MYSQL_USER=orguser
      - MYSQL_PASSWORD=secret1234
     healthcheck:
      test: mysql --user=orguser --password=secret1234 -e 'show databases;'
      interval: 2s
      timeout: 2s
      retries: 50
   testfrontend:
     image: kvalitetsit/gooioidwsrest:1.1.14
     command:
      - "-config"
      - "/caddy/config.json"
     volumes:
      - ./frontend.json:/caddy/config.json
     ports:
      - 8080:80
   videoapiservice:
     image: kvalitetsit/medcom-video-api:latest
#     image: kvalitetsit/medcom-video-api:1.5.8
     environment:
      - jdbc_url=jdbc:mysql://mysql:3306/videodb?useSSL=false
      - jdbc_user=orguser
      - jdbc_pass=secret1234
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole

      - userservice_url=""
      - userattributes.role.key="dk:medcom:video:role"
      - userservice_token_attribute_userrole="dk:medcom:video:role"
      - userservice_token_attribute_organisation="dk:medcom:organisation_id"
      - userservice_token_attribute_username="dk:medcom:email"
      - userservice_token_attribute_email="dk:medcom:email"
      - mapping.role.provisioner="meeting-provision"
      - mapping.role.admin="meeting-admin"
      - mapping.role.user="meeting-user"
      - mapping.role.meeting_planner="meeting-planner"

      - scheduling.template.default.conferencing.sys.id=22
      - scheduling.template.default.uri.prefix=""
      - scheduling.template.default.uri.domain="vconf-test.dk"
      - scheduling.template.default.host.pin.required=true
      - scheduling.template.default.host.pin.range.low=10000
      - scheduling.template.default.host.pin.range.high=99999
      - scheduling.template.default.guest.pin.required=true
      - scheduling.template.default.guest.pin.range.low=10000
      - scheduling.template.default.guest.pin.range.high=99999
      - scheduling.template.default.vmravailable.before=15
      - scheduling.template.default.max.participants=0
      - scheduling.template.default.end.meeting.on.end.time=false
      - scheduling.template.default.uri.number.range.low=10000
      - scheduling.template.default.uri.number.range.high=99990
      - scheduling.template.default.ivr.theme=10
      - scheduling.info.citizen.portal=""
      - short.link.base.url=""

      - organisationtree.service.endpoint=""
      - overflow.pool.organisation.id=0

      - audit.nats.disabled=true
     depends_on:
      mysql:
       condition: service_healthy
   documenatation-and-test:
     image: kvalitetsit/medcom-video-api-documentation:latest
     environment:
      - BASE_URL=/test
     ports:
      - 80:8080
