name: Java CI with Maven

on:
  push:
    branches: [ docker ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
# Checkout source code
    - uses: actions/checkout@v2

# Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

# Login to docker hub using secrets in GitHub.
    - name: Login to docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Version
      run: lsb_release -a

    - name: docker version
      run: docker -v

    - name: Build and test
      run: ./build/build.sh

    - name: docker images
      if: ${{ always() }}
      run: docker image ls

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v1.0.0
      with:
        jacoco-csv-file: medcom-video-api-qa/target/site/jacoco-aggregate/jacoco.csv

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Update coverage badge
      run: ./build/badge-update.sh

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: medcom-video-api-qa/target/site/jacoco-aggregate/

    - name: Tag service dev docker image
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api:latest kvalitetsit/medcom-video-api:dev

    - name: Push service dev docker image
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api:dev

    - name: Tag service git id docker image
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api:latest kvalitetsit/medcom-video-api:${{ github.sha }}

    - name: Push service git id docker image.
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api:${{ github.sha }}

    - name: Tag documentation dev docker image
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api-documentation:latest kvalitetsit/medcom-video-api-documentation:dev

    - name: Push documentation dev docker image
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api-documentation:dev

    - name: Tag documentation git id docker image
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api-documentation:latest kvalitetsit/medcom-video-api-documentation:${{ github.sha }}

    - name: Push documentation git id docker image.
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api-documentation:${{ github.sha }}

    - name: Is Tag Build
      id: tag
      if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Push latest service docker image
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api:latest

    - name: Tag version service docker image
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api:latest kvalitetsit/medcom-video-api:${{ steps.tag.outputs.VERSION }}

    - name: Push version service docker image.
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api:${{ steps.tag.outputs.VERSION }}

    - name: Push latest documentation docker image
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api-documentation:latest

    - name: Tag version documentation docker image
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-tag.sh kvalitetsit/medcom-video-api-documentation:latest kvalitetsit/medcom-video-api-documentation:${{ steps.tag.outputs.VERSION }}

    - name: Push version documentation docker image.
      if: ${{ steps.tag.conclusion != 'skipped' }}
      run: ./build/docker-push.sh kvalitetsit/medcom-video-api-documentation:${{ steps.tag.outputs.VERSION }}
